services:
  - type: web
    name: guestjourney-analytics
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_ADMIN_EMAIL
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false
      - key: NODE_VERSION
        value: 18
